### ISSUE TITLE
PROJ: Experiment with Stale Repos GHA

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/open#11]
## MENTOR
@decause-gov

## BRIEF DESCRIPTION
GitHub released an action that identifies "stale" repositories within an Org. We'd like to experiment with this so we can recommend a deployment/usage strategy for CMS.

## SCOPING (Minutes, Hours, Days, Weeks, Months, Years)
- Hours

## REQUIRED DELIVERABLES
- GitHub Action Deployed to our org

## DESIRED DATE WINDOW (June, July, August, Any)
- June or Any

## NOTES/INSPO

https://github.blog/2023-06-05-announcing-the-stale-repos-action/

**Comment by Firebird1029** [comment]
@decause-gov @natalialuzuriaga @IsaacMilarky PR is ready for review here: https://github.com/DSACMS/open/pull/42

**Comment by Firebird1029** [comment]
Ready for re-review here: https://github.com/DSACMS/metrics/pull/215

**Comment by natalialuzuriaga** [comment]
8/12:
- PR is merged 🥳
