### ISSUE TITLE
Create CIF Final Presentation Deck/Demos

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/open#36]

**Comment by decause-gov** [comment]
07/29:
- Demos that will occur by EoS (end of summer): 
- 08/12 (Mon) - CIF CMS Data Science Community Demo Day (30 Minutes) (@ ??? time)
- 08/14 (Wed) - CIF Demo Day @ 2pm EST (Dunno if you are specifically demo'ing, but you're attending)
- 08/16 (Fri) - CIF DSAC Demo Day @ 11am EST 
- 08/19 (Mon)- OSPO Advisory Board Meeting

**Comment by decause-gov** [comment]
08/05:
08/12 (Mon) - CIF CMS Data Science Community Demo Day (30 Minutes) (@ 10am EST)
08/14 (Wed) - CIF Demo Day @ 2pm EST (Dunno if you are specifically demo'ing, but you're attending)
08/16 (Fri) - CIF DSAC Demo Day @ 11am EST
08/19 (Mon) - OSPO Advisory Board Meeting

This year's starter template deck: https://docs.google.com/presentation/d/1d-4qC-UQIPTFxtg0JsawoDkr_BEzx-CsPi9jX1Wvi-M/edit?usp=sharing

Last year's Deck: https://docs.google.com/presentation/d/1zua2KPMuoPTf6-p699YDgHgC3rAERbMh96jeyJPHYrc/edit#slide=id.g23c0131ad68_0_33

Latest "preamble" OSPO slides in DEFCON deck: https://docs.google.com/presentation/d/1AV16SssPkcdWXFVqiiD895nyarbN0-ue/edit

GOAL: Deliver a 30 minute presenatation (20-25 minutes of content, 5-10 minutes of Q&A) covering as many rotations and lessons learned from the summer as possible.
GOAL: Include images where possible (screenshots, mockups, metrics, etc...), Include URLs to repositories always, include all member's of the cohort, include a thank you for anyone you'd like to recognize from the experience, use the DSAC branding (template above.)

**Comment by IsaacMilarky** [comment]
8/9:

- Brandon just needs to record
- Nick just needs to update some slides but is almost done

**Comment by natalialuzuriaga** [comment]
8/12:
- Data Science Office Hours presentation went well 🥳 
- Presenting one more time during DSAC staff/all hands
- Hit the 30 minute mark
- Incorporate feedback from Nat

**Comment by decause-gov** [comment]
08/15:
- https://docs.google.com/presentation/d/1d-4qC-UQIPTFxtg0JsawoDkr_BEzx-CsPi9jX1Wvi-M/edit?usp=sharing
- Presenting tomorrow at DSAC Staff
- Nat/Murt/decause will take a look, leave some comments if applicable.

**Comment by decause-gov** [comment]
08/30:
Final Deck: https://docs.google.com/presentation/d/1OcpyZGRnvGXqj1unBFDjjSMmFtjILyd-ocjRi0hHucM/edit?usp=sharing
Final Deck Export: [CIF-2024-FINAL-SUBMISSION.pdf](https://github.com/user-attachments/files/16818452/CIF-2024-FINAL-SUBMISSION.pdf)
