### ISSUE TITLE
Generate End-of-summer Gource Visualization for CIF

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/open#37]

**Comment by decause-gov** [comment]
08/05:
- Set up a Gource Hacksesh where Isaac and the Cohort make the Gource Viz!
- GOAL: Video in 2-3 minutes tops. Showing all the rotation work done over the summer. Adding captions for what each pull-request/rotation title accomplished. Do this manually for now ;)
- https://github.com/dsacms/cms-gource has some example data/configs.

**Comment by IsaacMilarky** [comment]
8/9:

- Try to have hack session on next Tuesday afternoon (optional if people can't join)

**Comment by natalialuzuriaga** [comment]
8/12:
- Isaac prepped for this, scheduled a work sesh / demo for tomorrow! Show how gource works and generating logs

**Comment by decause-gov** [comment]
08/15:
- @IsaacMilarky has prepared the gource video! We just need captions, and to tweak the background image (to include the CIF logo perhaps?)
- IDEA: use semver/changelog standards so that we can auto-generate captions.
- IDEA: use the generic 'created a repo' (will only show the test repos, reverse scorecard, and murai)
- IDEA: use week numbers? Halfway point?
- CAPTIONS Examples: "Shipped filtering/sorting for metrics" or "added Code.json"
- IDEA: Add COCOMO Stats for the summer!

> Based on GS-8 Salary ($46k/year)
> Total Cost Before Fellows: $7,913,803.12
> Total Cost After Fellows: $9,604,219.95
> Total Value added: $1,690,416.82
> Total Months before fellows: 162.23527250789488
> Total Months after fellows: 173.01902296077182
> Total estimated months spent: 10.783750452876944
> Total People before fellows: 59.82357210991555
> Total People after fellows: 67.45278823181192
> Total estimated People required: 7.62921612189637

**Comment by IsaacMilarky** [comment]
8/16:
Created the CIF gource visualization and uploaded it to slack in #dsac-ospo and #dsac-general
