### ISSUE TITLE
Prototype Multimodal LLM Mural Assistant with Ollama

### ISSUE THREAD

**Issue by CreativeNick** [DSACMS/open#38]
## MENTOR
- Matthew Artz

## BRIEF DESCRIPTION
Mural maps can be very complex and vast, containing a lot of important information that is forgotten overtime. A multimodal LLM assistant could be useful in helping people who are looking at a mural map for the first time and need to quickly understand/extract info from it, such as learning more about a network of sticky notes.

## SCOPING
- 2-3 weeks

## SKILLS NEEDED
Ollama, LLMs, APIs

## REQUIRED DELIVERABLES
- Research with models (LLM & Vision) will work best together
- Combine both models to create a multimodal model large enough to read screenshots thoroughly
- (Optional) Create prototype intractable UI

## DESIRED DELIVERY WINDOW
- August

**Comment by decause-gov** [comment]
07/26:
- Experimenting with different models. Having some issues with some models are too small to work with screenshots. Having trouble reading text (too small). Suspect it is related to being too small of a model.
- Working on combining different LLMs and Models (LLMs + Vision Models) so we can read/understand screenshots of murals.
- ACTION: Break down the ticket make it more granular with steps and completion goals.
- ACTION: Let's document this bigtime. Any questions/problems you have, please write them down, even just in plain text, and we'll generate docs at the end of the summer.

**Comment by decause-gov** [comment]
07/29:
- Looking into different kinds of models
- Repo is created, in github.cms.gov: https://github.cms.gov/JUB9/mural-ollama
- Model download almost complete, then testing
- Goal: Finalize which model to use, create a basic UI, and additional python scripts to view mural. If not finished, update the project proposal ticket with the details.

**Comment by decause-gov** [comment]
08/02:
- LLaVa experiments, mid-range, 8GBs, performed decently, but, the larger model seemed to perform better with the higher-res/detailed images.
- Spoke with Matthew Arts, do have access to cloud GPUs, and google collab notebooks. Will need to look into that more. Macbooks can't handle a 20GB model even.
- Looking into cloud compute would be more helpful.
- Tried LLama 3.1. It was just infinitely loading. Will ask in #ai-community if anyone has used it. Wouldn't be surprised if there were bugs.
- IDEA: create a quick GUI, before moving on to larger models, by today.
- GOAL: Capture findings, document results, look into outbound tier1 review for pushing to DSACMS, and transferring github.cms.gov repo to DSAC org.

**Comment by CreativeNick** [comment]
08/05:
- Still experiencing Llama3.1 issues
- Cleaning up and bugfixing UI

**Comment by IsaacMilarky** [comment]
8/9:

- Did a lot of gui work
- Concerns about README and other misc files.
- Will either write rough README and then update later or use cookiecutter first
- Changes are not yet pushed

**Comment by CreativeNick** [comment]
8/9:
- First prototype completed!
- Link to CMS.gov repo: https://github.cms.gov/JUB9/mural-ollama/

### Notes for future fellows or those who want to continue working on this project:

Currently, prompt engineering is the only method used for fine-tuning the model. While I don't had the time to explore other options, here are some methods that I'd look into:
- Breaking down the screenshot into smaller chunks/tokens
- Training the model with Mural screenshots
- OCR (Optical Character Recognition) tool integration
- Confidence scores

This initial prototype uses LLaVa:13b, which is only 8 GB! I have attempted using LLaVa:34b, which is 20 GB, but it runs incredibly slowly (to the point of unusable) due to the hardware of our CMS macbooks. I believe using a larger model like LLaVa:34b would significantly improve the performance of the LLM. The 8GB model can get a general idea of the Mural screenshot (the one you provided me) but I believe it struggles with small text. This then causes it to hallucinate and make up information. I think a larger model would make it be able to analyze larger images that have more detail or smaller text. This then brings me to my next suggestion:

Cloud compute. CMS has AWS cloud GPUs which would offer significantly greater computational power. I recommend talking to Matthew Artz about this if you are interested in learning more.

**Comment by natalialuzuriaga** [comment]
8/12:
- Need to discuss README
- May need to get rid of screenshot due to it being an internal mural board
- ACTION: Go over tier 1 outbound checklist to publish on DSACMS GH Org, schedule time with Nat/Isaac to fix cookiecutter on Nick's machine + review outbound checklist results

**Comment by CreativeNick** [comment]
8/12: 
- DSACMS Repo now public! https://github.com/DSACMS/mural-ollama
- New issue opened for future fellows: https://github.com/orgs/DSACMS/projects/9/views/1?pane=issue&itemId=74724471
