### ISSUE TITLE
PROJ: Create Default GitHub Community Health File for DSACMS

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/open#9]
## MENTOR
@decause-gov

## BRIEF DESCRIPTION
We want to ship a .github repo to our org, so that new repositories created within it will automatically comply with our GitHub Community Health Guidelines, and CMS Open Source Policy and best practices. 

## SCOPING
- days/weeks

## REQUIRED DELIVERABLES
 - A .github repo with as many of the required community health files to pass GitHub guidelines
 - LICENSE.md, README.md, and SECURITY.md files for LVL1
 - ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, and CONTRIBUTING.md for LVL2
 - MAINTAINERS.md, and CHANGELOG.md for LVL3
 - GOVERNANCE.md for LVL4

## DESIRED DATE WINDOW (June, July, August, Any)
- June

## NOTES/INSPO
This would create a massive floor-raising effect for our projects across the board!

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by Gaelan** [comment]
Looks like most of these are already done for @DSACMS - is the project to do the same for @CMSGov?

**Comment by decause-gov** [comment]
Nice Work @natalialuzuriaga!
